### ISSUE TITLE
РИГА

### ISSUE THREAD

**Issue by dubinsky** [digitaljudaica/alter-rebbe.org#213]
- [ ] заказать дело из рижского архива которое цитирует Дубнов (похоже, это не LNA 208);
- [ ] связать с соответствующим документом Дубнова;
- [ ] что там ещё описано из интересующего нас?

**Comment by michaelko58** [comment]
https://drive.google.com/open?id=10ETiq_GdKlkn_j3qixW_qluDD-Lb4lms
Это дело об арестованных хасидах

**Comment by michaelko58** [comment]
LNA Riga, I-2-208
 Канцелярия Лифлянд.,Курлянд. и Эстлянд. губернатора.
О сопровождении пяти арестованных евреев с конвоем в Вильно.

**Comment by michaelko58** [comment]
Похоже это не то, что цитирует Дубнов. Его цитата где-то в другом месте, хоть и о рижской цензуре.

**Comment by dubinsky** [comment]
see #268
