### ISSUE TITLE
МИНСК - НИАРБ

### ISSUE THREAD

**Issue by michaelko58** [digitaljudaica/alter-rebbe.org#214]
Собрать все дела, которые нас интересуют

**Comment by michaelko58** [comment]
NIARB ф 2096 оп.1, д.19
жителей Любавичи, получивших .. после пожара 1858 г.

**Comment by michaelko58** [comment]
NIARB ф 1297 оп.1, д.25207
Витебский, могилевский, смоленский губернатор
Донос Кисина на Митлер Ребе

**Comment by michaelko58** [comment]
NIARB ф 1297 оп.1, д.611
Витебский, могилевский, смоленский губернатор
Следствие по доносу Кисина на Митлер Ребе

**Comment by dubinsky** [comment]
see #268
