### ISSUE TITLE
CAHJP

### ISSUE THREAD

**Issue by dubinsky** [digitaljudaica/alter-rebbe.org#215]
https://drive.google.com/drive/folders/1kI42DJVmsvLR4WxDGCkHMmlSpyRSQMFr?usp=sharing
Фотографии из иерусалимского каталога разных дел, в том числе в Виленском, Рижском и Минском архивах, которые нам интересны.

Идентифицировать интересующие нас дела и перечислить их в #268;
если известны координаты дела - завести коллекцию для него.

**Comment by michaelko58** [comment]
РГИА, 1309,1, 119
Сословие попечителей презрения разоренных в 1812 г.
Прошения лиц, пострадавших от военных действий, о выдаке пособий по губерниям Гродненской,
Витебской, Могилевской и др., в т.ч.прошение Щтерны Лейбовным вдовы раввина м. Ляды р.Шнеера Залмана, подписанное его сыном р. Дов Бером Шнеерсоном, раввином м. Любавичи (подпись на иврите).
В деле - Открытый лист для проезда р. Шнеера Залмана с семейством во внутрение губернии России.

**Comment by michaelko58** [comment]
LVIA Vilniua 378 B/S 1868 3470
Виленский генерал-губернатор. Общий отдел.
Полицейское постановление: проведение в жузнь правительственного постановления 
В нем Закон против  противившихся мерам, предлагавшимся Г.Р. Державиным в 1798
его привлечением доверенного лица Ноты Ноткина

**Comment by michaelko58** [comment]
LVIA Vilniua 378 B/S 1799 2a extract
Виленский генерал-губернатор. Общий отдел.
"Об устройстве в Польше порядка и прочих распряжений служащих балгу народа"
- переписка по взаимным претензиям "кагала" и "каролинов"
- список книг виленской цензуры

**Comment by michaelko58** [comment]
Российская национальная библиотека, РО, ф.152, оп.1, д.211
Военский К.Е.
Перевод на русской послания Шнеур Залмана из Ляд к российским евреям
Рукописная копия из Военно-ученого архива

**Comment by michaelko58** [comment]
Российская национальная библиотека, РО, Евр IV , 203
1852 - 1857 г.
דברי חסידות חבד
ילקוט דרשות "תורת אדמו"ר הזקן" , נכתב ע"י בנו

**Comment by michaelko58** [comment]
Все дела, мной найденные , переписал. Что не исключает, что в каталоге может быть еще что-то.

**Comment by dubinsky** [comment]
@michaelko58 всегда может быть что-то ещё, но надо заканчивать куски и переходить к следующим. Вот что тебе сейчас надо сделать: проверь, что в списке коллекций на входной странице сайта есть всё, что ты описал  в комментариях к этому билетику, и если да - закрой его.

**Comment by michaelko58** [comment]
Эти два из архивов  библиотеки у нас отсуствуют

**Comment by dubinsky** [comment]
@michaelko58 что значит "у нас отсутствуют"? Если "у нас пока нет фотографий" - это сейчас не важно; если "не перечислены на входной странице" - смотри внимательней: http://www.alter-rebbe.org/collections/rnb203/index.html
