### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by dubinsky** [digitaljudaica/alter-rebbe.org#299]
- [x] add prev/next/list/this for facsimiles;
- [x] add collection reference to the navigation bar in document view;
- [ ] добавить к навигации (или заменить её на) выползающее меню;
  - https://github.com/forestryio/jekyll-menus
  - https://stackoverflow.com/questions/8340170/jekyll-automatically-highlight-current-tab-in-menu-bar
  - https://jekyllcodex.org/without-plugin/simple-menu/
  - https://thinkshout.com/blog/2014/12/creating-dynamic-menus-in-jekyll/
- [ ] add title as tool-tips to the navigation bar links;

**Comment by michaelko58** [comment]
В чем сомнения? Меню уплотнить?

**Comment by dubinsky** [comment]
@michaelko58 сомнения в том, нужно ли ещё какое-то меню в добавок к уже имеющейся (и сегодня улучшенной) навигации; точнее, у меня есть уверенность, что нет, не нужно; просто как честный человек я решил заострить этот вопрос до того, как закрыть билетик.

**Comment by michaelko58** [comment]
Все ок. Пока материал подчинен меню.

**Comment by dubinsky** [comment]
@michaelko58 никакого меню у нас сейчас нет (а как следствие - ему ничего не подчинено); этот билетик - о СОЗДАНИИ меню, которое откуда-то выезжало бы. По-моему, ничего такого делать не нужно, и я этот билетик хочу закрыть. "Всё ок" - это твоё согласие, что выезжающее меню не нужно - или несогласие?

**Comment by michaelko58** [comment]
Закрывай. Пока мы не вышли за пределы двух арестов - все в порядке

**Comment by dubinsky** [comment]
Я ни хрена не понимаю, о каких пределах ты говоришь: в списке дел, откывающимся при нажатии слова `Дела` - 24 дела... Но билетик закрываю :)
