### ISSUE TITLE
Контексты имён

### ISSUE THREAD

**Issue by dubinsky** [digitaljudaica/alter-rebbe.org#313]
@michaelko58 ты хотел какого-то в списках упоминаний.
Я сегодня подкрутил молотилку так, что теперь эти списки разделены по делам,
а упоминания в других поименованых штуковинал ссылаются на на штуковины
(а не на список всех имён как раньше). Посмотри, пожалуйста.

Я не очень понимаю, что ещё можно сделать.

А: Я показываю одну ссылку на документ даже если имя в нём упомянуто неоднократно.

1) Можно попробовать показывать по-разному различать ссылки из туши документа
и из его метаданных, но не вижу смысла, да и смотри "А".

2) Можно попробовать показывать названия документов в этом списке. Не вижу смысла,
да и список разрастётся.

3) Можно попробовать показывать названия документов в пузырьках, проступающих при помахивании над номером документа; опять же - не вижу смысла.

Можно отказаться от ограничения "А", и перечислять все места, где имя упомянуто, даже если их много в одном документе. Списки при этом разрастутся. К тому же, чтобы ссылка вела
в нужное место, надо будет добавлять в упомянаниях атрибут `xml:id`, а то не на что сослаться. Если документ небольшой (типа, на экран), это визуально всё равно мало что даст:
место ссылки всё равно не проступиот на верху экрана.

Мне кажется, что ты хотел чуть-ли не давать цитату из места ссылки, т.е. кусок текста, содержащего в себе само имя. Списки разрастутся чудовищно. К тому же, это нетривиально,
поэтому пока я делать ничего не буду, а подожду, чтобы ты мне объяснил, чего ты конкретно хочешь. Прямо тут вот.

**Comment by michaelko58** [comment]
Шана това! Сделал ты все замечательно. 
Одной ссылки на документ достаточно.
А что сделать с именами в целом надо подумать. Сейчас начал переговоры с Ильей, чтобы задействовать его не как расшифровщика (которым не все довольны) а как профессионального историка.

**Comment by dubinsky** [comment]
Так как технически пока ничего делать на надо - закрываю.
