### ISSUE TITLE
Гирш Давыдович

### ISSUE THREAD

**Issue by dubinsky** [digitaljudaica/alter-rebbe.org#559]
Собрать информацию о Г. Давидовиче в файле https://github.com/digitaljudaica/alter-rebbe.org/blob/master/docs/research/Гирша_Давыдовичъ.md
и привести её в удобоваримый вид

**Comment by michaelko58** [comment]
А разве она утверждает, что это тот? Он вообще из Вильно, а не сродной витебщины.

**Comment by michaelko58** [comment]
Ты прав, книжка новая, надо разобраться.

**Comment by michaelko58** [comment]
https://www.litres.ru/olga-minkina/syny-rahili-evreyskie-deputaty-v-rossiyskoy-imperii-1772-1825/chitat-onlayn/

**Comment by michaelko58** [comment]
https://books.google.nl/books?id=AkiaBQAAQBAJ&pg=PP127&dq=%D0%9E%D0%BB%D1%8C%D0%B3%D0%B0+%D0%9C%D0%B8%D0%BD%D0%BA%D0%B8%D0%BD%D0%B0++%D1%81%D1%8B%D0%BD%D1%8B+%D0%A0%D0%B0%D1%85%D0%B5%D0%BB%D0%B8+%D0%93%D0%B8%D1%80%D1%88+%D0%94%D0%B0%D0%B2%D0%B8%D0%B4%D0%BE%D0%B2%D0%B8%D1%87&hl=nl&sa=X&ved=0ahUKEwjn85Xdv9jlAhUBJFAKHat1DOIQ6AEIKTAA#v=onepage&q=%D0%9E%D0%BB%D1%8C%D0%B3%D0%B0%20%D0%9C%D0%B8%D0%BD%D0%BA%D0%B8%D0%BD%D0%B0%20%20%D1%81%D1%8B%D0%BD%D1%8B%20%D0%A0%D0%B0%D1%85%D0%B5%D0%BB%D0%B8%20%D0%93%D0%B8%D1%80%D1%88%20%D0%94%D0%B0%D0%B2%D0%B8%D0%B4%D0%BE%D0%B2%D0%B8%D1%87&f=false

с большой долей вероятности может быть отождествлен

**Comment by dubinsky** [comment]
@michaelko58 собери весь твой диалог с Василием, включая упомянутые там источники и электронный адрес авторши в файл - или Давидовича, или, если хочешь, сделай новый, как образец ранее упомянавшейся тобой исследовательской части сайта.

**Comment by michaelko58** [comment]
Думаю добавить это в твой список исследователей документов

**Comment by dubinsky** [comment]
@michaelko58 нех. думать - трясти надо! Ты добавь, а я подумаю, куда сдвинуть.

**Comment by michaelko58** [comment]
Вероятно, тот же И. Нахимович упоминается в документе 1803 г. как «виленского еврейского кагала синдик, еврей Еремиан Нахимович», который скрепил своей подписью доверенность, выданную виленским кагалом поверенному Гирше Давидовичу[299].
299 Гессен Ю.И. Евреи в России. С. 237.
Примечательно, что депутаты, возможно, не ограничивали свою деятельность рамками комитета. Так, «еврейский депутат Виленской и Гродненской губерний» Гирша Давидович 31 августа 1803 г. подал прошение «на высочайшее имя» через Третий департамент Сената, т. е. действовал подобно еврейским «поверенным» конца XVIII в.[450] Несмотря на то что и в самом прошении, и во всеподданнейшем рапорте Сената Давидович именуется «депутатом»[451], в доверенности, выданной Давидовичу виленским кагалом 13 августа 1803 г., не упоминаются ни депутаты, ни Еврейский комитет. В доверенности, подписанной «Виленского еврейского кагала синдиком» Еремианом Нахимовичем[452], оговаривалось право Давидовича «от имени целого общества Литовско-Виленской губернии по делам кагала, купечества, обывателей и всего еврейского общества в Правительствующий Сенат и прочие присутственные места прошения подавать»[453]. Возможно, Давидович являлся не депутатом, а поверенным, и именование его «депутатом» в документах Сената отражает терминологическую нечеткость в определениях различных форм еврейского представительства.
450 Бершадский С.А. Положение о евреях 1804 г. Опыт исторического исследования оснований и мотивов этого законодательного памятника // Восход. 1895. № 6. С. 49. Несмотря на заглавие, данная работа представляет собою тематическую подборку документов, снабженных минимальным исследовательским комментарием. Публикатор ограничился указанием на Третий департамент Сената.
451 Там же. С. 60. В рапорте Сената – «депутат, избранный от евреев Виленской и Гродненской губерний».
452 По всей видимости, тот же «синдик» виленского кагала И. Нахимович, который 15 января 1795 г. от имени «еврейского общества» Вильно и Гродно подал прошение Н.В. Репнину (Акты, издаваемые Виленской комиссиею для разбора древних актов. Вильна, 1902. Т. XXIX. С. 468).
453 Гессен Ю.И. Евреи в России. С. 237–238. Гессен не указал источник полностью опубликованной им доверенности, а также воздержался от какого-либо анализа этого документа. Скорее всего, он не относился к комплексу документов, использованному С.А. Бершадским (см. выше, примечание 64). По классификации Гессена, Давидович относится к «поверенным», обращавшимся к власти по частным вопросам.
Г. Давидович с большой долей вероятности может быть отождествлен с Гиршем Давидовичем из Вильно, подавшим в 1798 г. донос на хасидов, приведший к аресту цадика Шнеура Залмана и его наиболее влиятельных последователей из Вильно. Примечательно, что, используя в своих целях известные тогда опасения правительства, Давидович обвинял хасидов во «вредных для государства поступках» и даже намекал на возможную связь идей хасидизма с французской революцией[455]. Поскольку среди делегировавшего Давидовича еврейского населения Виленской и Гродненской губерний преобладали противники хасидов – миснагиды, то успешное выступление Давидовича против хасидов, наглядно продемонстрировавшее также его способность искусно использовать «язык власти», могло послужить веским доводом в пользу его избрания. Если автор доноса 1798 г. и депутат Давидович – одно и то же лицо, то здесь мы имеем дело с чрезвычайно интересной транс формацией традиционно презираемого еврейским обществом доносчика в уважаемую и значительную фигуру. Отношение к доносчику могло претерпевать изменения под воздействием раскола еврейского общества на хасидов и миснагидов. Доносчик, выражавший интересы одной из сторон, утрачивал свои негативные коннотации и становился своего рода «штадланом».
455 Гессен Ю.И. К истории религиозной борьбы среди русских евреев. С. 251. По мнению Гессена, поскольку при расследовании дела властям не удалось обнаружить Г. Давидовича, он либо успел скрыться, либо «это было вымышленное лицо».
Упомянут еще Шмуйло Давидович
Собранием были избраны также «прибавочные особы», которые должны были заседать «в совете» с депутатами: Шмуйло Давидович из Вильно (в случае его отказа на его место должен был быть выбран еврей из Волынской губернии, которого назначит раввин Хаим Мордух Марголис из Дубно[889]) и Элиша, сын пинского раввина Вигдоровича.

**Comment by michaelko58** [comment]
ISBN: 978-5-4448-0302-8
Ольга Юрьевна Минкина ««Сыны Рахили». Еврейские депутаты в Российской империи. 1772–1825»
