### ISSUE TITLE
Дела, которые мы ищем

### ISSUE THREAD

**Issue by michaelko58** [digitaljudaica/alter-rebbe.org#776]
РГИА, 468 фонд, 43, дело 529, стр. 71 (Из а-Маасар а-ришон)
Письмо Эстер, жены реб Меира императору 
Там же стр. 77
Дневник правления Литвы
Там же стр. 74
Письмо виленского кагала

РГАДА, 7, 1, дело 3140 стр.54 - копия в ГИАЛ (Лита), сборник 378 (Канцелярия генерал-губернатора), 1799. дело 178, стр.75
Отрывок из дневника виленского правления от 30 июня 1798 года

Другие документы из ГИАЛ (Лита), сборник 378 (Канцелярия генерал-губернатора)

Возможные поиски: 
Виленский еврейский кагал. Государственный исторический архив Литвы
https://cdiak.archives.gov.ua/baza_rech_pol/Data/LT_LVIA_620.xml 
Коллекция документов финансово-имущественных дел еврейского населения на территории Речи Посполитой и Галиции. Центральный государственный исторический архив Украины во Львове (ЦГИАЛ Украины)
https://cdiak.archives.gov.ua/baza_rech_pol/Data/UA_CSHAUL_141.xml

http://vilnius.penki.lt/fondy.html
620 | 1 опись57 дел | Vilniaus miesto žydų kahalasВиленский еврейский кагал 1764-1921

**Comment by michaelko58** [comment]
Заказ Галине в вильнюсский архив

Документы, нас интересующие.
Из фонда №378 "Канцелярия Виленского военного генерал-губернатора":

1) 1799 Следственное дело по жалобам Мойжеша Ошеровича В деле опись произведенному следствию (лл. 512-514)
2) "Об устройстве в Польше порядка и прочих распряжений служащих балгу народа" переписка по взаимным претензиям "кагала" и "каролинов" список книг виленской цензуры
3)  Об устройстве в Польше порядка, претензии Виленского кагала и карлинского еврейского общества
4) Материалы следствия по делу о финансовой деятельности бывших виленских кагальных, уволенных за злостные финансовые нарушения по жалобам местных хасидов (лл. 357-403)
5)1800 2-2. О выборах кагала
6)Полицейское постановление: проведение в жизнь правительственного постановления В нем Закон против противившихся мерам, предлагавшимся Г.Р. Державиным в 1798 его привлечением доверенного лица Ноты Ноткина.
7) 1799. дело 178, стр.75 Отрывок из дневника виленского правления от 30 июня 1798 года

Что касается фонда №567  "Попечитель Виленского учебного округа"
, то мы им пока заниматься не будем.

**Comment by michaelko58** [comment]
Возможные поиски: 
Виленский еврейский кагал. Государственный исторический архив Литвы
https://cdiak.archives.gov.ua/baza_rech_pol/Data/LT_LVIA_620.xml 
Коллекция документов финансово-имущественных дел еврейского населения на территории Речи Посполитой и Галиции. Центральный государственный исторический архив Украины во Львове (ЦГИАЛ Украины)
https://cdiak.archives.gov.ua/baza_rech_pol/Data/UA_CSHAUL_141.xml

**Comment by michaelko58** [comment]
http://vilnius.penki.lt/fondy.html
620 | 1 опись57 дел | Vilniaus miesto žydų kahalasВиленский еврейский кагал 1764-1921

**Comment by michaelko58** [comment]
1) 1799 Следственное дело по жалобам Мойжеша Ошеровича В деле опись произведенному следствию (лл. 512-514) - 3 скана по 4,10 евро;
2) "Об устройстве в Польше порядка и прочих распряжений служащих балгу народа" переписка по взаимным претензиям "кагала" и "каролинов" - 7 сканов по 4,10 евро и список книг виленской цензуры - 7 сканов по 4,10 евро;
3)  Об устройстве в Польше порядка, претензии Виленского кагала и карлинского еврейского общества - 19 сканов по 4,10 евро;
4) Материалы следствия по делу о финансовой деятельности бывших виленских кагальных, уволенных за злостные финансовые нарушения по жалобам местных хасидов (лл. 357-403) - 46 сканов по 2,90 евро;
5)1800 2-2. О выборах кагала - 30 сканов по 2,90 евро;
6)Полицейское постановление: проведение в жизнь правительственного постановления В нем Закон против противившихся мерам, предлагавшимся Г.Р. Державиным в 1798 его привлечением доверенного лица Ноты Ноткина. - в деле похожие 2 копии этого "державинского" документа, на их сличение я не тратила время - 6 сканов по 2,90 евро;
7) 1799. дело 178, стр.75 Отрывок из дневника виленского правления от 30 июня 1798 года - стр. 75-77 об. - 3 скана по 4,10 евро.

**Comment by dubinsky** [comment]
Слито в #268
