### ISSUE TITLE
Поиск и тэги

### ISSUE THREAD

**Issue by dubinsky** [digitaljudaica/alter-rebbe.org#812]
@michaelko58 
Посетителя в первую очередь интересуют не дела, а темы.
Нужен список тем, который разветвляется на дела или даже на их отдельные листы.
Народ предлагает добавить поиск по сайту (или облако тегов).

В принципе я согласен, и то, и другое должно быть.
Для того, чтобы это сделать, надо перевести сайт на динамическую платформу: невозможно заготовить ответы на все поисковые запросы, а таги должны иметь возможность добавлять пользователи.

Платформа нашей мечты, разговоры о которой ведутся уже 30 лет, естественно, должна всё это поддерживать. Когда что-то в этой области сдвинется достаточно, чтобы сайт мог в неё вписаться - всё сделаем.

С другой стороны, такого рода заявки в контексте "что дейчас должно быть" выглядят как необдуманные. Например, что именно надо искать? Все персонажи, места и организации и так должны быть перечислены...

**Comment by michaelko58** [comment]
Есть идеал, а есть минимум. Сделать поиск слова  по сайту ( заменяя в том числе на страый шрифт по простым формулам) - разве это сложно?

**Comment by dubinsky** [comment]
Да, это сложно. Во-первых, надо подключить что-то вроде Lucene (https://lucene.apache.org/), причём с индексаторами, понимающими русскую орфографию, в том числе и старую. Во-вторых, у нас тексты с тагами, что сбивает обычные индексаторы; см. "Information Retrieval from Annotated Texts " (http://www.wisdom.weizmann.ac.il/~fraenkel/Papers/annot.ps).

**Comment by dubinsky** [comment]
Передвиныто в `app.alter-rebbe.org`.
