### ISSUE TITLE
НИАБ

### ISSUE THREAD

**Issue by michaelko58** [digitaljudaica/alter-rebbe.org#828]
- [x] НИАБ - дело Цемах Цедека: Дело 14, 1 эксп., 1841 г.:
   "О расследовании деятельности хасидов в Витебске и Могилёве"
  с материалами о Любавичском раввине Менделе Шнеерсоне ("миттел-ребе"). 
- [x] засунуть "описания" и "фотографии" дел, которые нас пока не интересуют, в Google Drive;

**Comment by dubinsky** [comment]
Дело сделано :)
