### ISSUE TITLE
Зачёркивания

### ISSUE THREAD

**Issue by dubinsky** [digitaljudaica/alter-rebbe.org#960]
от @Basileus4 :
Кстати, есть маленькая проблема с отображением, связанная с зачеркнутыми словами и символами. Во-первых, зачеркивание в конце такого слова стыкуется со следующим словом, во вторых, в цифрах оно не очень заметно, особенно одиночных. Зачеркнутая семерка выглядит как вполне правильная, только с палочкой посередине, как если бы была не печатной, а письменной. В четверку тоже надо вглядываться. Может быть, это у меня так видно.

- [x] http://www.alter-rebbe.org/collections/rgada/documents/289.html - с. 296 с перечеркнутой "7", 298 с перечеркнутой "8", 307 с "5" - @Basileus4 пытаюсь выделить зачёркивания цветом ;
- [x] в том же документе номер "313 об." выглядит зачеркнутым, хотя в тегах перечеркивания нет - @Basileus4 зачёркивания в конце 313 и в начале 313об были заключены в общий тег, который вобрал в себя и незачёркнутый номер страницы; исправляю;
- [ ] в 367 зачеркнутая запятая совсем не получилась, вышел новый странный знак. Т.е. зачеркивание пошло выше символа. Поскольку здесь это не принципиально, может быть, совсем убрать эту запятую? Другое дело, что в дальнейшем нужно что-то придумать, может понадобиться - @Basileus4 не нашёл попытки зачеркнуть запятую в документе 367;
- [x] и пример стыковки. Там же (http://www.alter-rebbe.org/collections/rgada/documents/289.html) 291: имѣть такіе или 292 с нижня свѣтитъ - @Basileus4 ко-где внутрь тегов `del` попал пробел в конце зачёркнутого текста; это приводит к стыковкам (а к такой ситуации иногда приводит тот механизм форматирования TEI, которым Вы пользуетесь: он переносит закрывающий тег `del` на новую строку, и вот...);

**Comment by Basileus4** [comment]
Например, http://www.alter-rebbe.org/collections/rgada/documents/289.html - с. 296 с перечеркнутой "7", 298 с перечеркнутой "8", 307 с "5"

**Comment by Basileus4** [comment]
В том же документе номер "313 об." выглядит зачеркнутым, хотя в тегах перечеркивания нет.

**Comment by Basileus4** [comment]
В 367 зачеркнутая запятая совсем не получилась, вышел новый странный знак.

**Comment by Basileus4** [comment]
Т.е. зачеркивание пошло выше символа. Поскольку здесь это не принципиально, может быть, совсем убрать эту запятую? Другое дело, что в дальнейшем нужно что-то придумать, может понадобиться

**Comment by Basileus4** [comment]
И пример стыковки. Там же (http://www.alter-rebbe.org/collections/rgada/documents/289.html) 291: имѣть такіе или 292 с нижня свѣтитъ

**Comment by Basileus4** [comment]
По цвету и по 313 об. - ОК.
В 367 я уже убрал запятую: там это можно было сделать без ущерба - в некоторых местах знаки препинания ставились едва не случайным образом, четких правил не было; иногда нельзя понять, запятая это, лихой росчерк канцеляриста или клякса. )
по стыкам с зачеркнутым - правильно я понимаю, что выход пока простой: отмечать такие места, чтобы потом исправлять вручную?

**Comment by dubinsky** [comment]
> по стыкам с зачеркнутым - правильно я понимаю, что выход пока простой: отмечать такие места, чтобы потом исправлять вручную?

Да.
